<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>

		<img src="/img/twitter_logo.png" class="menuIco" />
        
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->perfil["nome"] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil["tweets"] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil["seguindo"] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->perfil["seguidores"] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="POST" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
						placeholder="O que você está pensando?" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>
			<?php foreach($this->view->tweets as $idx => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						
						<p><strong><?= $tweet["nome"] ?></strong> <span class="text text-muted"><?= $tweet["data"] ?></span></p>
						<p><?= $tweet["tweet"] ?></p>

						<br />
						
						<?php if($_SESSION["id"] == $tweet["id_usuario"]){ ?>
							<div class="col d-flex justify-content-end">
								
								<a href="/acao?acao=remover&id=<?= $tweet['id'] ?>" class="btn btn-danger fas fa-trash-alt"></a>
							</div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

			<nav class="mt-2">
				<ul class="pagination justify-content-center">

					<?php if($this->view->pagina_atual == 1) { ?>
						<li class="page-item disabled">
							<a class="page-link" href="#">Anterior</a>
						</li>
					<?php } else { ?>
						<li class="page-item">
							<a class="page-link" href="/timeline?pagina=<?= $this->view->pagina_atual - 1 ?>">Anterior</a>
						</li>
					<?php } ?>

					<?php
						if($this->view->pagina_atual <= 5) {
							for($i = 1; $i <= 5; $i++) { ?>
								<?php if($this->view->pagina_atual == $i) { ?>
									<li class="page-item active">
										<a class="page-link"><?= $i ?></a>
									</li>
								<?php } else { ?>
									<li class="page-item">
										<a class="page-link" href="/timeline?pagina=<?= $i ?>"><?= $i ?></a>
									</li>
								<?php } ?>	
					<?php }} else { ?>

						<li class="page-item">
							<a class="page-link" href="/timeline?pagina=1">1</a>
						</li>
						<li class="page-item disabled">
							<a class="page-link"">...</a>
						</li>

						<?php for($i = $this->view->pagina_atual - 2; $i <= $this->view->pagina_atual; $i++) { 
							if($this->view->pagina_atual == $i) { ?>
								<li class="page-item active">
									<a class="page-link"><?= $i ?></a>
								</li>
							<?php } else { ?>
								<li class="page-item">
									<a class="page-link" href="/timeline?pagina=<?= $i ?>"><?= $i ?></a>
								</li>
							<?php } ?>							
					<?php }} ?>

					<?php
						if($this->view->pagina_atual >= $this->view->qtd_paginas - 4) {
							for($i = $this->view->pagina_atual + 1; $i <= $this->view->qtd_paginas; $i++) { ?>
								<?php if($this->view->pagina_atual == $i) { ?>
									<li class="page-item active">
										<a class="page-link"><?= $i ?></a>
									</li>
								<?php } else { ?>
									<li class="page-item">
										<a class="page-link" href="/timeline?pagina=<?= $i ?>"><?= $i ?></a>
									</li>
								<?php } ?>							
					<?php }} else {
						for($i = $this->view->pagina_atual + 1; $i <= $this->view->pagina_atual + 2; $i++) { 
							if($this->view->pagina_atual == $i) { ?>
								<li class="page-item active">
									<a class="page-link"><?= $i ?></a>
								</li>
							<?php } else { ?>
								<li class="page-item">
									<a class="page-link" href="/timeline?pagina=<?= $i ?>"><?= $i ?></a>
								</li>
							<?php } ?>							
					<?php } ?>

					<li class="page-item disabled">
						<a class="page-link"">...</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="/timeline?pagina=<?= $this->view->qtd_paginas ?>"><?= $this->view->qtd_paginas ?></a>
					</li>
					
					<?php } ?>


					<?php if($this->view->pagina_atual == $this->view->qtd_paginas) { ?>
						<li class="page-item disabled">
							<a class="page-link" href="#">Próximo</a>
						</li>
					<?php } else { ?>
						<li class="page-item">
							<a class="page-link" href="/timeline?pagina=<?= $this->view->pagina_atual + 1 ?>">Próximo</a>
						</li>
					<?php } ?>
					
					
				</ul>
			</nav>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>